import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import * as path from 'node:path'
import * as os from 'node:os'
import { promises as fs } from 'node:fs'

import { validateTrackFile, isTrackFile } from '../../src/shared/schemas/track-file'
import { generateDisplacementCurve } from '../../src/shared/pipeline/displacement-curve'
import type { WalkFrameTrack } from '../../src/shared/pipeline/walk-tracker'
import { trackFileName, writeTrackFile, readTrackFile } from '../../src/main/pipeline/track-file'
import type { TrackFile } from '../../src/shared/types/track-file'

let tmpDir: string

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'petalive-track-'))
})

afterEach(async () => {
  await fs.rm(tmpDir, { recursive: true, force: true })
})

function trackXs(xs: number[]): WalkFrameTrack[] {
  return xs.map((x, i) => ({ frameIndex: i, centroidX: x, centroidY: 50, feetY: 110, foreground: true }))
}

describe('validateTrackFile / isTrackFile (track.json schema, §5.3)', () => {
  it('accepts a track.json generated by generateDisplacementCurve', () => {
    const file = generateDisplacementCurve(trackXs([60, 63, 66, 70]), 30)
    expect(validateTrackFile(file)).toEqual([])
    expect(isTrackFile(file)).toBe(true)
  })

  it('accepts manual keypoint corrections', () => {
    const file: TrackFile = {
      version: 1,
      fps: 30,
      frameCount: 3,
      offsets: [0, 1.2, 2.4],
      keypoints: [{ frame: 1, offset: 1.5 }]
    }
    expect(validateTrackFile(file)).toEqual([])
  })

  it('rejects wrong version, non-positive fps, non-integer frameCount', () => {
    expect(validateTrackFile({ version: 2, fps: 30, frameCount: 1, offsets: [0], keypoints: [] }).length).toBeGreaterThan(0)
    expect(validateTrackFile({ version: 1, fps: 0, frameCount: 1, offsets: [0], keypoints: [] }).length).toBeGreaterThan(0)
    expect(
      validateTrackFile({ version: 1, fps: 30, frameCount: 1.5, offsets: [0], keypoints: [] }).length
    ).toBeGreaterThan(0)
  })

  it('rejects offsets length mismatch and non-finite values', () => {
    expect(
      validateTrackFile({ version: 1, fps: 30, frameCount: 3, offsets: [0, 1], keypoints: [] }).length
    ).toBeGreaterThan(0)
    expect(
      validateTrackFile({ version: 1, fps: 30, frameCount: 2, offsets: [0, NaN], keypoints: [] }).length
    ).toBeGreaterThan(0)
  })

  it('rejects keypoints out of range, unsorted, or duplicate frame', () => {
    const base = { version: 1, fps: 30, frameCount: 4, offsets: [0, 1, 2, 3] }
    expect(
      validateTrackFile({ ...base, keypoints: [{ frame: 4, offset: 3 }] }).length
    ).toBeGreaterThan(0)
    expect(
      validateTrackFile({ ...base, keypoints: [{ frame: 2, offset: 2 }, { frame: 1, offset: 1 }] }).length
    ).toBeGreaterThan(0)
    expect(
      validateTrackFile({ ...base, keypoints: [{ frame: 1, offset: 1 }, { frame: 1, offset: 2 }] }).length
    ).toBeGreaterThan(0)
  })
})

describe('trackFileName (§5.3)', () => {
  it('produces <clip_id>.track.json', () => {
    expect(trackFileName('walk_right_01')).toBe('walk_right_01.track.json')
  })
})

describe('writeTrackFile / readTrackFile (§12.1)', () => {
  it('round-trips a generated track.json', async () => {
    const file = generateDisplacementCurve(trackXs([60, 63, 66, 70]), 30)
    const written = await writeTrackFile(tmpDir, 'walk_right_01', file)

    expect(path.basename(written)).toBe('walk_right_01.track.json')
    const read = await readTrackFile(tmpDir, 'walk_right_01.track.json')
    expect(read).toEqual(file)
  })

  it('rejects writing an invalid track file', async () => {
    const bad = { version: 1, fps: 30, frameCount: 3, offsets: [0, 1], keypoints: [] }
    await expect(writeTrackFile(tmpDir, 'bad', bad as unknown as TrackFile)).rejects.toThrow(
      /invalid track file/
    )
  })

  it('throws when the file does not exist', async () => {
    await expect(readTrackFile(tmpDir, 'missing.track.json')).rejects.toThrow()
  })
})
